### ISSUE TITLE
Apply width and height attributes to <svg>

### ISSUE THREAD

**Issue by pugson** [andrey-hohlov/posthtml-inline-svg#1]
Hey, this is a really cool plugin. Thanks for making it!

It would be great if you could apply `width` and `height` attributes that get passed down to the SVG when rendered.

```html
<icon src="check.svg" class="icon" width="32" height="32"></icon>
```

to
```html
<svg xmlns="http://www.w3.org/2000/svg" width="32" height="32">
  <!-- svg content -->
</svg>
```

**Comment by andrey-hohlov** [comment]
Hi, @pugson 
Thanks you for the feedback!

Can you share the icon you tried?
I checked with test icon and ```width``` and ```height``` attributes applied correctly.

**Comment by pugson** [comment]
Wow, my bad! I assumed it wouldn't work but it does. Thanks again!!
