### ISSUE TITLE
help find your package

### ISSUE THREAD

**Issue by Scrum** [andrey-hohlov/posthtml-inline-svg#3]
@andrey-hohlov  Hi, I am a posthtml package maintainer, I found your package because you have a posthtml package in dependencies. I think it will be easier for people to find your package if you add it to the list of plugins [here](https://github.com/posthtml/posthtml#plugins) and [here](https://github.com/posthtml/posthtml-plugins/), and of course the first thing to do in the posthtml organization itself - I can move your package to the posthtml organization for more popularity, for this it will be necessary to add me to this repository and then I will transfer it. The package itself will remain under your control.

let me know about any decision you make, i will understand if you are not interested

**Comment by andrey-hohlov** [comment]
Hi @Scrum 
I think it's a good idea.

Can you explain please: 
1. I should add you to Collaborators, right?
2. How new versions will be published on npm?

**Comment by Scrum** [comment]
Hi @andrey-hohlov 

> I should add you to Collaborators, right?

No, I have to be `owner` in order to be able to move your package to the organization while retaining all rights to the package (with the option to return it back to you).

> How new versions will be published on npm?

Regarding publication, if you would like other participants in the organization to be able to provide operational support, then yes it will be necessary to give rights to the NPM, for starters, you can give me an `scrum` account.

**Comment by andrey-hohlov** [comment]
@Scrum I decided to keep this repository under my account.

I want people to use it and I have created pull-request into lists of plugins right now.
But also I'm trying to learn and build my story here. This small plugin will be very helpful for it.

I appreciate your help - list of plugins, pull-request and some approaches I saw and will introduce in my code. Thank you!

**Comment by Scrum** [comment]
> @Scrum I decided to keep this repository under my account.

Any decision you make is right. Let me know if suddenly your decision changes.

> But also I'm trying to learn and build my story here. This small plugin will be very helpful for it.

Let me know if I can be of any use to you in your undertakings.

Good luck 🚀
